# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"triee": "00_core.ipynb",
         "cov": "01_oval_clean.ipynb",
         "numpts": "01_oval_clean.ipynb",
         "Points": "01_oval_clean.ipynb",
         "vlen": "01_oval_clean.ipynb",
         "major": "01_oval_clean.ipynb",
         "minor": "01_oval_clean.ipynb",
         "x_vec": "01_oval_clean.ipynb",
         "dot": "01_oval_clean.ipynb",
         "ang": "01_oval_clean.ipynb",
         "rat": "01_oval_clean.ipynb",
         "major_length": "01_oval_clean.ipynb",
         "minor_length": "01_oval_clean.ipynb",
         "transform_x": "01_oval_clean.ipynb",
         "transform_y": "01_oval_clean.ipynb",
         "cos": "01_oval_clean.ipynb",
         "sin": "01_oval_clean.ipynb",
         "theta": "01_oval_clean.ipynb",
         "x": "01_oval_clean.ipynb",
         "y": "01_oval_clean.ipynb",
         "x_oval": "01_oval_clean.ipynb",
         "y_oval": "01_oval_clean.ipynb",
         "Points_map": "01_oval_clean.ipynb",
         "boundary": "01_oval_clean.ipynb",
         "xx": "01_oval_clean.ipynb",
         "y1": "01_oval_clean.ipynb",
         "y2": "01_oval_clean.ipynb",
         "layer_init": "02_NN.ipynb",
         "linear": "02_NN.ipynb",
         "fetch": "03_NN_numpy.ipynb",
         "mnist": "03_NN_numpy.ipynb",
         "kaiming_uniform": "03_NN_numpy.ipynb",
         "kaiming_normal": "03_NN_numpy.ipynb",
         "Linear": "03_NN_numpy.ipynb",
         "MSELoss": "03_NN_numpy.ipynb",
         "CELoss": "03_NN_numpy.ipynb",
         "SGD": "03_NN_numpy.ipynb",
         "Adam": "03_NN_numpy.ipynb"}

modules = ["core.py",
           "to_submit.py",
           "nn.py",
           "nnsig.py"]

doc_url = "https://Kelvinthedrugger.github.io/HWs/"

git_url = "https://github.com/Kelvinthedrugger/HWs/tree/master/"

def custom_doc_links(name): return None
