# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"triee": "00_core.ipynb",
         "cov": "oval_clean.ipynb",
         "numpts": "oval_clean.ipynb",
         "Points": "oval_clean.ipynb",
         "vlen": "oval_clean.ipynb",
         "major": "oval_clean.ipynb",
         "minor": "oval_clean.ipynb",
         "x_vec": "oval_clean.ipynb",
         "dot": "oval_clean.ipynb",
         "ang": "oval_clean.ipynb",
         "rat": "oval_clean.ipynb",
         "major_length": "oval_clean.ipynb",
         "minor_length": "oval_clean.ipynb",
         "transform_x": "oval_clean.ipynb",
         "transform_y": "oval_clean.ipynb",
         "cos": "oval_clean.ipynb",
         "sin": "oval_clean.ipynb",
         "theta": "oval_clean.ipynb",
         "x": "oval_clean.ipynb",
         "y": "oval_clean.ipynb",
         "x_oval": "oval_clean.ipynb",
         "y_oval": "oval_clean.ipynb",
         "Points_map": "oval_clean.ipynb",
         "boundary": "oval_clean.ipynb",
         "xx": "oval_clean.ipynb",
         "y1": "oval_clean.ipynb",
         "y2": "oval_clean.ipynb"}

modules = ["core.py",
           "to_submit.py"]

doc_url = "https://Kelvinthedrugger.github.io/multnormal/"

git_url = "https://github.com/Kelvinthedrugger/multnormal/tree/master/"

def custom_doc_links(name): return None
