# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"triee": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://HWs.github.io/multnormal/"

git_url = "https://github.com/HWs/multnormal/tree/master/"

def custom_doc_links(name): return None
